gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Pie_Welcome::
	.string "Oh, wait!\p"
	.string "Before you go, a message from this\n"
	.string "hack's creator:\p"
	.string "Welcome to Pokémon Dynastic Emerald!\p"
	.string "This is a difficulty hack with modern\n"
	.string "mechanics, many quality of life\l"
	.string "changes, and massive Pokémon variety!\p"
	.string "You can build your team using almost\n"
	.string "any Pokémon from the first nine\l"
	.string "generations, Before you get started,\l"
	.string "you'll need, to choose a difficulty\l"
	.string "setting. Currently you can choose\l"
	.string "between Dynastic or Kaizo.\p"
	.string "Please select a mode to learn more\n"
	.string "about it.\p"
	.string "$"

gText_Pie_DynasticMode::
	.string "In Dynastic Mode, Trainers will have\n"
	.string "decent teams, with their normal effects,\l"
	.string "for example Roxanne has Permanent Sand.\p"
	.string "This difficulty is recommended\n"
	.string "cause it is the most Normal Mode,\l"
	.string "At The Moment. There will be an\p"
	.string "even easier mode in the future :D\p"
	.string "Is this the difficulty you want?\p"
	.string "$"

gText_Pie_KaizoMode::
	.string "In Kazio Mode, Trainers are designed\n"
	.string "to be so Hard it makes u Rage Quit.\p"
	.string "The game also puts more restrictions\n"
	.string "on you, such as no removing of weather,\l"
	.string "or terrain, the AI is also improved\l"
	.string "and Moves are restriced for the player.\l"
	.string "and much much more making it truly a\l"
	.string "Renewed Kaizo Experience.\p"
	.string "This difficulty is NOT recommended\n"
	.string "if ur new to Hard Rom Hacks or\l"
	.string "if ur just a casual player.\l"
	.string "cause this is THE HARDEST mode in this\l"
	.string "rom cause this mode was designed to be\l"
	.string "harder than EK and we all know how hard\l"
	.string "Is this the difficulty you want?\p"
	.string "$"

gText_Pie_WhichDifficulty::
	.string "Which difficulty would you like to\n"
	.string "play on?$"

gText_Pie_LevelCapExplain::
    .string "Great! Now, this hack has Level Caps\n"
    .string "just so Players don't Overlevel for\l"
    .string "each gym\p"
	.string "$"

gText_Pie_DynasticLevelCap::
	.string "$"

gText_Pie_Regions::
    .string "Now, there's one last thing\n"
    .string "to decide.\p"
    .string "This hack lets you choose Your Own\n"
    .string "Starter Region For any MonoType or\l"
    .string "MonoRegions You would like to do.\p"
    .string "Please choose a Region to continue.\p"
	.string ".$"

gText_Pie_Kanto::
	.string "Ah the KANTO Region, Such peacefull\n"
	.string "place. Is this the region you want?\p"
    .string "$"

gText_Pie_Johto::
	.string "Ah the JOHTO Region, Such cool place\n"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_Hoenn::
	.string "Ah the HOENN Region, Our Home Region\n"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_Sinnoh::
	.string "Ah the SINNOH Region, Region known for\n"
	.string "having gastrodon the best slug POKéMON.\p"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_Unova::
	.string "Ah the UNOVA Region, Region known for\n"
	.string "another fire fighting Type Combo Starter.\p"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_Kalos::
	.string "Ah the KALOS Region, Such cool place\n"
	.string "cause Goodra Exists.\p"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_Alola::
	.string "Ah the ALOLA Region, Region known for\n"
	.string "saying ALOHA too much.\p"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_Galar::
	.string "Ah the GALAR Region, I know nothing\n"
	.string "of the GALAR Region besides that it has the\l"
	.string "most OP Legendary's.\p"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_Paldea::
	.string "Ah the PALDEA Region, I know nothing\n"
	.string "of the PALDEA Region besides that it has the\l."
	.string "best starter in the game.\p"
	.string "Is this the region you want?\p"
	.string "$"

gText_Pie_WhichRegion::
	.string "Which Region would\n"
	.string "you like to play on?\p"
	.string "$"

gText_Pie_Documents::
	.string "Great! If you want more information,\n"
	.string "please check the out the Trainer Documents.\p"
	.string "They show you wich Trainer or Gym Leader\n"
	.string "Uses wich POKéMON they use.\p"
	.string "Finally, I hope you enjoy the hack!\n"
	.string "- Kaixer\p"
	.string "$"
